server:
  port: 8764
spring:
  application:
    name: eureka-client
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  zipkin:
    base-url: http://127.0.0.1:9411
    sender:
      type: web
  sleuth:
    sampler:
      probability : 1
management:
  endpoints:
    web:
      exposure:
        include: refresh,health,info,bus-refresh